### Analysis all

POST {{host}}/Analysis
Content-Type: application/json

{
    "All": true,
    "Days":[5, 20],
    "Types": ["GoldenCrossTradeCount", "GoldenCrossTransactionPrice"],
    "Date": "2020-09-25"
}

### Analysis some

POST {{host}}/Analysis
Content-Type: application/json

{
    "Codes": ['101730'],
    "Days":[5, 20],
    "Types": ["GoldenCrossTradeCount"]
}