### Code get Kosdaq

POST https://localhost:5001/Code/Load?stockType=Kosdaq
Content-Type: application/json

### Code get Kospi

POST https://localhost:5001/Code/Load?stockType=Kospi
Content-Type: application/json


### Code get konex

POST https://localhost:5001/Code/Load?stockType=Konex
Content-Type: application/json
