### Company get alerts

POST {{host}}/Company/Crawling/Alerts
Content-Type: application/json

### Company get all

POST {{host}}/Company/Crawling/Code?stockType=All
Content-Type: application/json

### Company get Kosdaq

POST {{host}}/Company/Crawling/Code?stockType=Kosdaq
Content-Type: application/json

### Company get Kospi

POST {{host}}/Company/Crawling/Code?stockType=Kospi
Content-Type: application/json


### Company get konex

POST {{host}}/Company/Crawling/Code?stockType=Konex
Content-Type: application/json
