### Crawling All

POST https://localhost:5001/Crawling
Content-Type: application/json

{
    "All": true,
    "Page": 5
}

### Crawling multi

POST https://localhost:5001/Crawling
Content-Type: application/json

{
    "Codes": ['118990','207760','206640','053030'],
    "Page": 1
}

### Crawling invalid one

POST https://localhost:5001/Crawling
Content-Type: application/json

{
    "Codes": ['294090'],
    "Page": 1
}



### Crawling valid one

POST https://localhost:5001/Crawling
Content-Type: application/json

{
    "Codes": ['294090'],
    "Page": 1
}
