### MockInvest Get

GET https://localhost:5001/MockInvest?UserId=elky

### MockInvest Get

GET https://localhost:5001/MockInvest?UserId=elky_1m


### MockInvest Refresh

POST https://localhost:5001/MockInvest/Refresh
Content-Type: application/json

{
    "UserId":"elky"
}


### MockInvest Refresh

POST https://localhost:5001/MockInvest/Refresh
Content-Type: application/json

{
    "UserId":"elky_1m"
}


### MockInvest Analysis-Buy

POST https://localhost:5001/MockInvest/Analysis-Buy
Content-Type: application/json

{
    "UserId":"elky",
    "Type": "GoldenCrossTransactionPrice",
    "Count":10,    
    "TotalPrice":10000000,
    "Date": "2020-09-15"
}

### MockInvest Analysis-Buy

POST https://localhost:5001/MockInvest/Analysis-Buy
Content-Type: application/json

{
    "UserId":"elky_1m",
    "Type": "GoldenCrossTransactionPrice",
    "Count":10,    
    "TotalPrice":100000,
    "Date": "2020-09-15"
}

### MockInvest Buy

POST https://localhost:5001/MockInvest/Buy
Content-Type: application/json

{
    "UserId":"elky",
    "Code": "053030",
    "Amount":100
}

### MockInvest Sell

POST https://localhost:5001/MockInvest/Sell
Content-Type: application/json

{
    "UserId":"elky",
    "All":true
}
