### User Create

POST {{host}}/User
Content-Type: application/json

{
    "UserId":"elky",
    "Balance": 100000000,
    "OriginBalance": 100000000,
    "AutoTrade": true,
    "AutoTradeCount": 10,
    "AnalysisType": "GoldenCrossTransactionPrice"
}

### User Get

GET {{host}}/User/5f688d482a5a62ab89dfbe07

### User Update

PUT {{host}}/User/5f688d482a5a62ab89dfbe07
Content-Type: application/json

{
    "Id": "5f608e55953dc198528c7e57",
    "UserId":"elky",
    "Balance": 100000000,
    "OriginBalance": 100000000,
    "AutoTrade": true,
    "AutoTradeCount": 10,
    "AnalysisType": "GoldenCrossTransactionPrice"
}

### User Delete

DELETE {{host}}/User/5f688d482a5a62ab89dfbe07

