### User Create

POST {{host}}/User
Content-Type: application/json

{
    "UserId":"elky",
    "Balance": 100000000,
    "OriginBalance": 100000000,
    "AutoTrade": true,
    "AutoTradeCount": 10,
    "AnalysisType": "GoldenCrossTransactionPrice"
}

### User Create

POST {{host}}/User
Content-Type: application/json

{
    "UserId":"elky_1m",
    "Balance": 1000000,
    "OriginBalance": 1000000,
    "AutoTrade": true,
    "AutoTradeCount": 10,
    "AnalysisType": "GoldenCrossTransactionPrice"
}

### User Get

GET {{host}}/User/5f5a25cc6e6fbaf1a5e7ccca

### User Update

PUT {{host}}/User/5f5eea74ea4f2840f4e1951b
Content-Type: application/json

{
    "UserId":"elky",
    "Balance": 100000000,
    "OriginBalance": 100000000,
    "AutoTrade": true,
    "AutoTradeCount": 10,
    "AnalysisType": "GoldenCrossTransactionPrice"
}

### User Delete

DELETE {{host}}/User/5f5a25cc6e6fbaf1a5e7ccca

